### ISSUE TITLE
[BUG] Unexpected action in ShowMore screen

### ISSUE THREAD

**Issue by pcy06** [hansei-hanum/hanum-frontend#50]
## 🤷 버그 내용
**어떤 버그인지 자세히 설명해주세요.**
When Showmore Page is opened, it only shows white screen and throws error (maybe due to data structure change on backend?)
Unnecessary get request when showmore page is opened (it should be called when user opens the app FIRST TIME, not when clicked showmore page)

## 🙇 재현 방법
**아래와 같이 작성해주세요.**

1. Just open app, then click "더 보기"

## ✨ 예상한 결과
**예상했던 결과는 어떤 것이었는지 알려주세요.**
Show "show more" page when user clicked "더 보기", not white screen
Only get self user object when app opened or logged in

**Comment by choi138** [comment]
Fix it in bug/49 branch 😁
